# Generated by Django 3.0.4 on 2020-03-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subs_type',
            name='type',
        ),
    ]
