# Generated by Django 3.0.4 on 2020-03-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_subs_type_sub_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subs',
            name='sub',
        ),
        migrations.AddField(
            model_name='subs',
            name='name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subs',
            name='sub_type',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subs_Type',
        ),
    ]
