# Generated by Django 3.0.4 on 2020-03-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200328_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Baked Ziti w/Mozzarella'), (2, 'Baked Ziti w/Meatballs'), (3, 'Baked Ziti w/Chicken')], max_length=64)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
