# Generated by Django 3.0.4 on 2020-03-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200328_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Garden Salad'), ('B', 'Greek Salad'), ('C', 'Antipasto'), ('D', 'Salad w/Tuna')], max_length=1)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
