# Generated by Django 3.0.4 on 2020-03-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_salads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner_Platters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Garden Salad'), ('B', 'Greek Salad'), ('C', 'Antipasto'), ('D', 'Baked Ziti'), ('E', 'Meatball Parm'), ('F', 'Chicken Parm')], max_length=1)),
                ('Dinner_Platters_type', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
