# Generated by Django 3.0.4 on 2020-03-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_regular_pizza_sicilian_pizza_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sicilian_pizza',
            name='numToppings',
        ),
        migrations.AddField(
            model_name='sicilian_pizza',
            name='numItems',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, 'Special')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regular_pizza',
            name='numToppings',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, 'Special')]),
        ),
        migrations.AlterUniqueTogether(
            name='regular_pizza',
            unique_together={('numToppings', 'type')},
        ),
    ]
