# Generated by Django 3.0.4 on 2020-03-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200329_1453'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dinner_platters',
            unique_together={('name', 'Dinner_Platters_type')},
        ),
        migrations.AlterUniqueTogether(
            name='pasta',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='salads',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='sicilian_pizza',
            unique_together={('numItems', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='subs',
            unique_together={('name', 'sub_type')},
        ),
        migrations.AlterUniqueTogether(
            name='toppings',
            unique_together={('name',)},
        ),
    ]
