# Generated by Django 3.0.4 on 2020-04-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200410_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regular_pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
