# Generated by Django 3.0.4 on 2020-04-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200410_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='price',
            field=models.IntegerField(),
        ),
    ]
