# Generated by Django 3.0.4 on 2020-04-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200410_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
