# Generated by Django 3.0.4 on 2020-04-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200410_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='name',
            field=models.IntegerField(choices=[(1, 'Cheese'), (2, 'Italian'), (3, 'Ham + Cheese'), (4, 'Meatball'), (5, 'Tuna'), (6, 'Turkey'), (7, 'Chicken Parmigiana'), (8, 'Eggplant Parmigiana'), (9, 'Steak'), (10, 'Steak + Cheese + Mushrooms'), (11, 'Steak + Cheese + Green Peppers'), (12, 'Steak + Cheese + Onions'), (13, 'Sausage, Peppers & Onions\t'), (14, 'Hamburger'), (15, 'Cheeseburger'), (16, 'Fried Chicken'), (17, 'Veggies')]),
        ),
    ]
