# Generated by Django 3.0.4 on 2020-04-10 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200410_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='placed_orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemtype', models.CharField(max_length=128)),
                ('item_id', models.IntegerField()),
                ('extra_cheese', models.BooleanField(null=True)),
                ('topping1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_topping', to='orders.Toppings')),
                ('topping2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_topping', to='orders.Toppings')),
                ('topping3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three_topping', to='orders.Toppings')),
            ],
        ),
    ]
