# Generated by Django 3.0.4 on 2020-04-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_placed_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='name',
            field=models.CharField(choices=[('Cheese', 'Cheese'), ('Italian', 'Italian'), ('Ham + Cheese', 'Ham + Cheese'), ('Meatball', 'Meatball'), ('Tuna', 'Tuna'), ('Turkey', 'Turkey'), ('Chicken Parmigiana', 'Chicken Parmigiana'), ('Eggplant Parmigiana', 'Eggplant Parmigiana'), ('Steak', 'Steak'), ('Steak + Cheese', 'Steak + Cheese'), ('Steak + Cheese + Mushrooms', 'Steak + Cheese + Mushrooms'), ('Steak + Cheese + Mushrooms + Green Peppers', 'Steak + Cheese + Mushrooms + Green Peppers'), ('Steak + Cheese + Mushrooms + Green Peppers + Onions', 'Steak + Cheese + Mushrooms + Green Peppers + Onions'), ('Sausage, Peppers & Onions', 'Sausage, Peppers & Onions'), ('Hamburger', 'Hamburger'), ('Cheeseburger', 'Cheeseburger'), ('Fried Chicken', 'Fried Chicken'), ('Veggies', 'Veggies')], max_length=128),
        ),
    ]
