# Generated by Django 3.0.4 on 2020-04-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20200413_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner_platters',
            name='Dinner_Platters_type',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=128),
        ),
        migrations.AlterField(
            model_name='dinner_platters',
            name='name',
            field=models.CharField(choices=[('Garden Salad', 'Garden Salad'), ('Greek Salad', 'Greek Salad'), ('Antipasto', 'Antipasto'), ('Baked Ziti', 'Baked Ziti'), ('Meatball Parm', 'Meatball Parm'), ('Chicken Parm', 'Chicken Parm')], max_length=128),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='name',
            field=models.CharField(choices=[('Baked Ziti w/Mozzarella', 'Baked Ziti w/Mozzarella'), ('Baked Ziti w/Meatballs', 'Baked Ziti w/Meatballs'), ('Baked Ziti w/Chicken', 'Baked Ziti w/Chicken')], max_length=128),
        ),
        migrations.AlterField(
            model_name='salads',
            name='name',
            field=models.CharField(choices=[('Garden Salad', 'Garden Salad'), ('Greek Salad', 'Greek Salad'), ('Antipasto', 'Antipasto'), ('Salad w/Tuna', 'Salad w/Tuna')], max_length=128),
        ),
    ]
