# Generated by Django 3.0.4 on 2020-04-16 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20200416_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinner_platters',
            old_name='Dinner_Platters_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='subs',
            old_name='sub_type',
            new_name='type',
        ),
        migrations.AlterUniqueTogether(
            name='dinner_platters',
            unique_together={('name', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='subs',
            unique_together={('name', 'type')},
        ),
    ]
