# Generated by Django 3.0.4 on 2020-04-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20200420_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='placed_orders',
            name='completed',
            field=models.BooleanField(null=True),
        ),
    ]
