# Generated by Django 3.0.4 on 2020-04-28 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_placed_orders_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placed_orders',
            name='topping1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_topping', to='orders.Toppings'),
        ),
        migrations.AlterField(
            model_name='placed_orders',
            name='topping2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_topping', to='orders.Toppings'),
        ),
        migrations.AlterField(
            model_name='placed_orders',
            name='topping3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three_topping', to='orders.Toppings'),
        ),
    ]
