# Generated by Django 3.0.4 on 2020-04-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20200428_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='placed_orders',
            name='username',
            field=models.CharField(default='xxx', max_length=128),
            preserve_default=False,
        ),
    ]
